# Copyright (c) 2015 Hong Quach

# This source file is licensed under the "MIT License."  Please see the LICENSE
# in this distribution for license terms.

- "name": "Purge Table1"
  description: "Purge data from table 1"
  archive_statement:
  purge_statement: "DELETE FROM Table1 WHERE created_date < current_timestamp + interval('10 minutes');"
  run_every_n_second: 5
  start_datetime: 2015-07-20 07:08:09

- "name": "Purge Table2"
  description: "Purge data from table 2"
  archive_statement:
  purge_statement:
  run_every_n_second: 10
  start_datetime: 2015-07-20 07:08:09